apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-v1
  labels:
    app: chatapp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp
      version: v1
  template:
    metadata:
      labels:
        app: chatapp
        version: v1
    spec:
      containers:
        - name: chatapp
          image: chatapp:v1
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-v1
spec:
  selector:
    app: chatapp
    version: v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
