apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-v2
  labels:
    app: chatapp
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp
      version: v2
  template:
    metadata:
      labels:
        app: chatapp
        version: v2
    spec:
      containers:
        - name: chatapp
          image: public.ecr.aws/r5m2h0c9/chatapp:v2
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-v2
spec:
  selector:
    app: chatapp
    version: v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
